#!/bin/php
<?php 

    require __DIR__."/app/private/api/resources/assets/database.php";
    use Everest\Assets\Database;
    $config = json_decode(file_get_contents(__DIR__."/app/private/api/config.json"), true);

    $config["DATABASE"]["HOSTNAME"] = "127.0.0.1";

    $db = new Database($config["DATABASE"]);

    $primary = "\033[38;2;91;121;68;1m";
    $reset = "\033[0m";
    $colors = ["primary"=>$primary, "reset"=>$reset];

    $options = [
        sprintf("%s-h, --help, Show this%s MENU%s", $colors["reset"], $colors["primary"], $colors["reset"]),
        sprintf("%s-t, --tables, Show all%s TABLES%s in the database", $colors["reset"], $colors["primary"], $colors["reset"]),
        sprintf("%s-u, --users, Show all%s USERS%s in the database", $colors["reset"], $colors["primary"], $colors["reset"])
    ];
    if (!isset($argv[1])) {
        $argv[1] = "-h";
    }
    switch ($argv[1]) {
        case $argv[1] == "-h" || $argv[1] == "--help" || $argv[1] == "help":
            echo("Options:\n");
            foreach ($options as $opt) {
                echo($opt."\n");
            }
            break;
        case $argv[1] == "-t" || $argv[1] == "--tables":
            $db->query("SELECT * FROM information_schema.tables where TABLE_SCHEMA = 'Everest'", $return);
            echo("Tables:\n");
            foreach ($return as $table) {
                echo(" ".$colors["primary"].$table["TABLE_NAME"].$colors["reset"]."\n");
            }
            break;
        case $argv[1] == "-u" || $argv[1] == "--users":
            $db->query("SELECT * FROM Everest.Users", $return);
            echo("Users:\n");
            if (count($return) == 0) {
                echo(" No Users In Database\n");
            }
            foreach ($return as $table) {
                echo(" ".$colors["primary"].$table["uuid"].$colors["reset"]."\n");
            }
    }

