FROM debian:bookworm

RUN apt update && apt upgrade -y && apt install p7zip-full python3-full python3-pip python3-venv procps -y

RUN mkdir /setup
WORKDIR /setup
RUN python3 -m venv env && env/bin/python3 -m pip install docker requests --quiet
COPY stream.py stream.py
RUN chmod +x stream.py

WORKDIR /
COPY startup.sh /startup.sh
RUN chmod +x /startup.sh

ENTRYPOINT [ "/startup.sh" ]